# Generated by Django 4.2.9 on 2024-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='ProductImages/')),
                ('quantity', models.IntegerField(max_length=5)),
                ('code', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
