# Generated by Django 4.2.9 on 2024-01-20 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='product.product')),
                ('image1', models.ImageField(null=True, upload_to='ExtraProductImage/')),
                ('image2', models.ImageField(null=True, upload_to='ExtraProductImage/')),
                ('image3', models.ImageField(null=True, upload_to='ExtraProductImage/')),
            ],
        ),
    ]
