# Generated by Django 4.2.9 on 2024-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='battery',
            field=models.TextField(default='No Information at the moment', max_length=2000),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='brand',
            field=models.TextField(default='No Information at the moment', max_length=2000),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='memory',
            field=models.TextField(default='No Information at the moment', max_length=2000),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='network',
            field=models.TextField(default='No Information at the moment', max_length=2000),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='processor',
            field=models.TextField(default='No Information at the moment', max_length=2000),
        ),
    ]
